-- Courses Table
create table courses (
  id bigint generated by default as identity primary key,
  title text not null,
  instructor text not null
);

-- Enrollments Table
create table enrollments (
  id bigint generated by default as identity primary key,
  student_name text not null,
  course_id bigint references courses(id)
);

insert into courses (title, instructor)
values('Node', 'Arr'),
('js', 'vrr'),
('html', 'err');

--this schema i used in supabase